stages:
    - test
    - build

test:
    stage: test
    script:
        - "./bin/test"
    tags:
        - android
        - java

build:
    stage: build
    script:
        - "./bin/build"
    tags:
        - android
        - java
