stages:
  - test
  - build

test:
  image: raatiniemi/android-environment:latest
  stage: test
  script:
    - ./bin/test
  tags:
    - docker

sonar:
  image: raatiniemi/android-environment:latest-jdk-8
  stage: test
  script:
    - ./bin/sonar
  only:
    - tags
  tags:
    - docker

build:
  image: raatiniemi/android-environment:latest
  stage: build
  script:
    - ./bin/build
  tags:
    - docker
